In [1]:
import matplotlib.pyplot as plt
import scipy.stats as st
import seaborn as sns
import pandas as pd
import numpy as np

In [9]:
st.norm.ppf(q=[0.005,0.995])

array([-2.5758293,  2.5758293])

In [5]:
5/np.sqrt(3)

2.886751345948129

In [11]:
st.norm.ppf(q=[0.005,0.995], loc=31, scale=np.sqrt(3.6))

array([26.11270752, 35.88729248])

In [17]:
st.norm.ppf(q=[0.005,0.995], loc=31, scale=(6/np.sqrt(10)))

array([26.11270752, 35.88729248])

In [23]:
(35.88729248-26.11270752)/2

4.887292479999999

In [24]:
st.norm.ppf(q=0.995)

2.5758293035489004